language: c
before_install:
  - sudo apt-get install libcurl4-gnutls-dev -qq
  - git clone https://github.com/clibs/clib.git /tmp/clib
  - sudo make -C /tmp/clib install
install: clib install
# not really a test, but w/e
script:
  - make example
  - ./example
